"""
   >>> import grok.tests.directive.argumenterror_fixture
   Traceback (most recent call last):
     ...
   TypeError: name takes...1...argument...3...given...
"""
