pyExceptions/__init__.py,sha256=yvT_DtxpDxYpAgrTjPGlH7VeTWnrOF3jqwYD6Aur9iQ,3028
pyExceptions-1.0.1.dist-info/LICENSE.md,sha256=DF4r-Jbsz_ZASY4VjV0ZZVaaHYkH9a20BkVExpq8doE,10571
pyExceptions-1.0.1.dist-info/METADATA,sha256=CG_c-Tc5FqTmHcIpv5-iaYyJCX8Nbvzxo3pNgw1CEjw,4102
pyExceptions-1.0.1.dist-info/WHEEL,sha256=EVRjI69F5qVjm_YgqcTXPnTAv3BfSUr0WVAHuSP3Xoo,92
pyExceptions-1.0.1.dist-info/top_level.txt,sha256=FCUx2KjHbxV3j3LdKBNNoUArrjEkFQTn9tzdqg_RCWs,13
pyExceptions-1.0.1.dist-info/RECORD,,
